import { Inter } from 'next/font/google';
import Home from './page';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {children}
        <h1 className='text-orange-600 border-2'>sdas</h1>
      </body>
    </html>
  );
}
